version: '3.8'

services:
  mcp_server:
    build: 
      context: ..
      dockerfile: mcp_server/Dockerfile
    container_name: mcp_server
    ports:
      - "8081:8081"
    volumes:
      - ./agents_db.json:/app/agents_db.json
    environment:
      - HOST=0.0.0.0
      - PORT=8081
    restart: always 